#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#General Configuration
spring:
  application:
    name: micro-services
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: service1-demo-dev
  #Databse configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices_demo?useTimezone=true&serverTimezone=UTC
    username: root
    password: ""
  #ORM configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
#Spring actuator Configurations
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'